### ISSUE TITLE
sending an incorrectly formatted message causes the ROS reciever to crash

### ISSUE THREAD

**Issue by mauricefallon** [ihmcrobotics/ihmc-open-robotics-software#25]
sending an incorrectly formatted footstep plan causes the controller to stop responding to all future messages. It also does this silently without any warning or printf.

My guess (extrapolating from the same kind of behaviour in Python) is that the Controller's ROS receiving thread crashes but the controller is still active.

This can be readily replicated in simulation by putting faulty robot_side id into a message. (the usual ids are 0 or 1)

```
footstep_data_list: 
  - 
    robot_side: 1
    location: 
      x: 0.154122320942
      y: -0.125441902765
      z: 0.0927366825572
    orientation: 
      x: 0
      y: 0
      z: 0
      w: 1
    predicted_contact_points: []
    trajectory_type: 1
    swing_height: 0.05
    unique_id: 0
  - 
    robot_side: 2  <------------------------------- should be either zero or one
    location: 
      x: 0.339570214942
      y: 0.133368271576
      z: 0.0928407591907
    orientation: 
      x: 0
      y: 0
      z: 0
      w: 1
    predicted_contact_points: []
    trajectory_type: 1
    swing_height: 0.05
    unique_id: 0
```
